
/// <summary>
/// 游戏配置<br/>
/// auto generated by Freemarker
/// </summary>
public class GameConfigKey
{

    /// <summary>
    /// Texture 最大宽度尺寸
    /// </summary>
    public const string texture_max_width = "texture_max_width";

    /// <summary>
    /// Texture 最大宽度尺寸
    /// </summary>
    public const string texture_max_height = "texture_max_height";

    /// <summary>
    /// 截屏图片大下 w
    /// </summary>
    public const string capture_screen_shot_tex_w = "capture_screen_shot_tex_w";

    /// <summary>
    /// 截屏图片大下 h
    /// </summary>
    public const string capture_screen_shot_tex_h = "capture_screen_shot_tex_h";

    /// <summary>
    /// 截屏原始 rect 大小 w
    /// </summary>
    public const string capture_screen_shot_rect_w = "capture_screen_shot_rect_w";

    /// <summary>
    /// 截屏图片位置偏移 w
    /// </summary>
    public const string capture_screen_shot_offset_w = "capture_screen_shot_offset_w";

    /// <summary>
    /// 截屏图片位置偏移 h
    /// </summary>
    public const string capture_screen_shot_offset_h = "capture_screen_shot_offset_h";

    /// <summary>
    /// Android相机截图存放位置
    /// </summary>
    public const string camera_screen_shots_path_android = "camera_screen_shots_path_android";

    /// <summary>
    /// 相机拍照类型id
    /// </summary>
    public const string camera_photo_type_id = "camera_photo_type_id";

    /// <summary>
    /// 相机拍照图片存储位置
    /// </summary>
    public const string camera_photo_path = "camera_photo_path";

    /// <summary>
    /// 录屏目标fps
    /// </summary>
    public const string ffmpeg_fps = "ffmpeg_fps";

    /// <summary>
    /// 录屏截图文件名字格式
    /// </summary>
    public const string ffmpeg_file_format = "ffmpeg_file_format";

    /// <summary>
    /// 录屏一张图片循环生成视频时间
    /// </summary>
    public const string ffmpeg_image_loop_video_time = "ffmpeg_image_loop_video_time";

    /// <summary>
    /// 录屏合成视频图片动画显示次数
    /// </summary>
    public const string ffmpeg_image_dynamic_texture_show_times = "ffmpeg_image_dynamic_texture_show_times";

    /// <summary>
    /// 颜色灰化系数
    /// </summary>
    public const string grey_color_vector = "grey_color_vector";

    /// <summary>
    /// 默认tile提示颜色
    /// </summary>
    public const string default_tile_prompt_color = "default_tile_prompt_color";

    /// <summary>
    /// 默认voxel提示颜色
    /// </summary>
    public const string default_voxel_prompt_color = "default_voxel_prompt_color";

    /// <summary>
    /// 默认voxel提示颜色1
    /// </summary>
    public const string default_voxel_prompt_color1 = "default_voxel_prompt_color1";

    /// <summary>
    /// voxel对象中心点位置
    /// </summary>
    public const string voxel_pivot = "voxel_pivot";

    /// <summary>
    /// voxel对象缩放参数
    /// </summary>
    public const string voxel_scale = "voxel_scale";

    /// <summary>
    /// voxel对象旋转速度
    /// </summary>
    public const string voxel_rotation_speed = "voxel_rotation_speed";

    /// <summary>
    /// grid路径补点距离间隔
    /// </summary>
    public const string grid_path_complement_point_dis = "grid_path_complement_point_dis";

    /// <summary>
    /// voxel路径补点最大距离间隔
    /// </summary>
    public const string voxel_path_complement_point_max_dis = "voxel_path_complement_point_max_dis";

    /// <summary>
    /// voxel路径补点最小距离间隔
    /// </summary>
    public const string voxel_path_complement_point_min_dis = "voxel_path_complement_point_min_dis";

    /// <summary>
    /// voxel相机缩放比率pc
    /// </summary>
    public const string camera_pinch_ratio_pc_voxel = "camera_pinch_ratio_pc_voxel";

    /// <summary>
    /// voxel相机拖动x比率pc
    /// </summary>
    public const string camera_swipe_x_pc_voxel = "camera_swipe_x_pc_voxel";

    /// <summary>
    /// voxel相机拖动y比率pc
    /// </summary>
    public const string camera_swipe_y_pc_voxel = "camera_swipe_y_pc_voxel";

    /// <summary>
    /// grid相机缩放比率pc
    /// </summary>
    public const string camera_pinch_ratio_pc_grid = "camera_pinch_ratio_pc_grid";

    /// <summary>
    /// grid相机拖动x比率pc
    /// </summary>
    public const string camera_swipe_x_pc_grid = "camera_swipe_x_pc_grid";

    /// <summary>
    /// grid相机拖动y比率pc
    /// </summary>
    public const string camera_swipe_y_pc_grid = "camera_swipe_y_pc_grid";

    /// <summary>
    /// voxel相机缩放比率android
    /// </summary>
    public const string camera_pinch_ratio_android_voxel = "camera_pinch_ratio_android_voxel";

    /// <summary>
    /// voxel相机拖动x比率android
    /// </summary>
    public const string camera_swipe_x_android_voxel = "camera_swipe_x_android_voxel";

    /// <summary>
    /// voxel相机拖动y比率android
    /// </summary>
    public const string camera_swipe_y_android_voxel = "camera_swipe_y_android_voxel";

    /// <summary>
    /// grid相机缩放比率android
    /// </summary>
    public const string camera_pinch_ratio_android_grid = "camera_pinch_ratio_android_grid";

    /// <summary>
    /// grid相机拖动x比率android
    /// </summary>
    public const string camera_swipe_x_android_grid = "camera_swipe_x_android_grid";

    /// <summary>
    /// grid相机拖动y比率android
    /// </summary>
    public const string camera_swipe_y_android_grid = "camera_swipe_y_android_grid";

    /// <summary>
    /// voxel相机缩放比率ios
    /// </summary>
    public const string camera_pinch_ratio_ios_voxel = "camera_pinch_ratio_ios_voxel";

    /// <summary>
    /// voxel相机拖动x比率ios
    /// </summary>
    public const string camera_swipe_x_ios_voxel = "camera_swipe_x_ios_voxel";

    /// <summary>
    /// voxel相机拖动y比率ios
    /// </summary>
    public const string camera_swipe_y_ios_voxel = "camera_swipe_y_ios_voxel";

    /// <summary>
    /// grid相机缩放比率ios
    /// </summary>
    public const string camera_pinch_ratio_ios_grid = "camera_pinch_ratio_ios_grid";

    /// <summary>
    /// grid相机拖动x比率ios
    /// </summary>
    public const string camera_swipe_x_ios_grid = "camera_swipe_x_ios_grid";

    /// <summary>
    /// grid相机拖动y比率ios
    /// </summary>
    public const string camera_swipe_y_ios_grid = "camera_swipe_y_ios_grid";

    /// <summary>
    /// 手指长按触发事件时间
    /// </summary>
    public const string finger_long_tap_time = "finger_long_tap_time";

    /// <summary>
    /// 相机自动重置位置速度
    /// </summary>
    public const string camera_auto_reset_pos_speed = "camera_auto_reset_pos_speed";

    /// <summary>
    /// 相机拍照图片帧率
    /// </summary>
    public const string camera_save_texture_fps = "camera_save_texture_fps";

    /// <summary>
    /// 相机拍照存储图片原始大小
    /// </summary>
    public const string camera_save_texture_size = "camera_save_texture_size";

    /// <summary>
    /// 相机拍照图片最大宽度
    /// </summary>
    public const string camera_save_texture_max_width = "camera_save_texture_max_width";

    /// <summary>
    /// 相机拍照图片最小宽度
    /// </summary>
    public const string camera_save_texture_min_width = "camera_save_texture_min_width";

    /// <summary>
    /// 相机拍照保存图片宽度基数
    /// </summary>
    public const string camera_save_texture_width_base = "camera_save_texture_width_base";

    /// <summary>
    /// 相机拍照保存图片颜色最大数量
    /// </summary>
    public const string camera_svae_texture_color_max_num = "camera_svae_texture_color_max_num";

    /// <summary>
    /// 相机拍照保存图片颜色最小数量
    /// </summary>
    public const string camera_svae_texture_color_min_num = "camera_svae_texture_color_min_num";

}

