
namespace tgame.consts
{

    /// <summary>
    /// 客户端预加载资源类型<br/>
    /// auto generated by Freemarker
    /// </summary>
    public class PreLoadResourceType
    {
        /// <summary>
        /// 模型资源
        /// </summary>
        public const int MODEL = 1;

        /// <summary>
        /// 特效资源
        /// </summary>
        public const int EFFECT = 2;

        /// <summary>
        /// 声音资源
        /// </summary>
        public const int SOUND = 3;

        /// <summary>
        /// 场景资源
        /// </summary>
        public const int SCENE = 4;

        /// <summary>
        /// ui资源
        /// </summary>
        public const int UI = 5;

    }

}


